feat(travis): add travis config and deploy script
TechnologyAdvice/local-sync pull request #11
Opened 2017-04-21 14:39 UTC by Fluidbyte

2017-04-21 16:21 UTC, levithomason requested changes

2017-04-21 16:21 UTC, levithomason commented on circle.yml
> -    - bash <(curl -s https://codecov.io/bash)
This got lost

2017-04-21 17:42 UTC, Fluidbyte commented on circle.yml
> -    - bash <(curl -s https://codecov.io/bash)
Fixed

2017-04-21 17:42 UTC, levithomason commented on deploy.sh
> +
We need `set -e` in here, else, this will run all steps even on a failure.

2017-05-10 17:09 UTC, levithomason approved these changes

2017-05-10 17:09 UTC, levithomason commented
I think this is good to go now.

2018-06-27 15:15 UTC, closed without merging

2018-06-27 22:47 UTC, levithomason commented
Good times

2018-06-27 23:23 UTC, davezuko commented
![image](https://user-images.githubusercontent.com/6439050/42004817-7207d300-7a26-11e8-856e-d4d65b8ad166.png)

2018-06-27 23:54 UTC, levithomason commented
2018

2018-06-28 19:42 UTC, kyleturco commented
Haha, yesterday was old PR closing day. Always a fun day.

2018-06-28 21:42 UTC, Fluidbyte commented
![Wow](https://i.imgur.com/l6Bx5j7_d.jpg)

2018-06-28 22:29 UTC, davezuko commented
Oh, hey @Fluidbyte . How's it going?

2018-06-28 23:18 UTC, Fluidbyte commented
Not bad, miss you guys.

2018-06-28 23:52 UTC, dvdzkwsk commented
Same. We should keep this thread open forever.